name:                euler
version:             0.1.0.0
github:              "rod-lin/euler"
license:             MIT
author:              "Rod Lin"
maintainer:          "rod.yeti@outlook.com"
copyright:           "2018 Rod"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/rod-lin/euler#readme>

dependencies:
- base >= 4.7 && < 5
- random
- containers
- permutation

library:
  source-dirs: src

executables:
  euler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - euler
