{-

Problem 12. Highly divisible triangular number

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

-}

module Euler.P12 where

import Euler.Util

numberOfDivisors :: Integer -> Integer
numberOfDivisors n
    | isPrime n = 2
    | otherwise = product (map ((+ 1) . fst . count 0 n) factors)
    where
        factors =
            filter (`divides` n) $
            takeWhile (<= ceiling (sqrt (fromInteger n))) primes

        -- return (e, r) where n = k ^ e * r and r does not divide n
count e n k =
    case n `mod` k of
        0 -> count (e + 1) (n `div` k) k
        r -> (e, n)

trigNum :: [Integer]
trigNum =
    map fst $
    iterate (\(a, n) -> (a + n, n + 1)) (1, 2)

-- 76576500
solve =
    first ((> 500) . numberOfDivisors) trigNum
