{-

Problem 29. Distinct powers

Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

-}

module Euler.P29 where

import Euler.Util

s = [ 2 .. 100 ] :: [Integer]

-- if the number a^b
-- is duplicate to another
-- number

-- solve = length $ do
--     b <- s
--     a <- s

--     let not_dup =
--             all (\d -> not (d `divides` b && a ^ (b `div` d) `elem` s))
--                 (takeWhile (< b) s)

--     -- exists d < b. a^(b/d)
--     -- d divides b and b / d in c
--     if not_dup then [1]
--     else []

-- 9183
solve =
    length (unique [ a ^ b | a <- s, b <- s ])
